### ISSUE TITLE
Some Bugs with Charms 1.2.2

### ISSUE THREAD

**Issue by iAmAutolocker** [YaBoiChips/Charms#2]
1) File name of Charms 1.2.2, when downloaded, becomes charms-1.0. A downgrade?
Steps to reproduce:
a) Download Charms 1.2.2 from curseforge
b) Observe file name

2) Saturation charm isn't working
Steps to reproduce:
a) Put saturation charm in charm container
b) Hunger bar/saturation doesn't get replenished

**Comment by YaBoiChips** [comment]
its the same thing just the file names got messed up srry, also the saturation also replenishes you to 2 saturation when you are under 2 saturation
